### ISSUE TITLE
Ubuntu Compile

### ISSUE THREAD

**Issue by NoahDragon** [bonafid3/FourierGL#1]
Thanks for this app, it's really intuitive to demonstrate the Fourier transform.

However, I always get the error that the opengl32.lib can't find under Ubuntu OS. I found the opengl32.lib is for VS build. I'm not familiar with QT and OpenGL, is there an alternative library in the Ubuntu to make the compilation work?

**Comment by bonafid3** [comment]
I have modified the .pro file slightly and should work on both Linux and Windows. You will need to re-run qmake for the changes to take effect. Please give some feedback in any case. Thank you!

**Comment by NoahDragon** [comment]
Thank you. I will try it tonight.

**Comment by NoahDragon** [comment]
The program crashes after compile. Not sure the reason.
```
Starting /home/projects/lab/build-fouriergl-qt5-Debug/fouriergl...
The program has unexpectedly finished.
/home/projects/lab/build-fouriergl-qt5-Debug/fouriergl crashed
```

**Comment by bonafid3** [comment]
Please try to run it in debug mode and you will see where it crashed. Send me the Stack info or just take a screenshot.

**Comment by NoahDragon** [comment]
I tried the debugger, it crash at the beginning, pop up a dialog showing that "segments fault"

![image](https://user-images.githubusercontent.com/5704064/31581452-8ba4e7a4-b13a-11e7-9193-b2307714d26a.png)

**Comment by bonafid3** [comment]
Please show the application output from Qt creator.

![screenshot 2017-10-15 21 53 15](https://user-images.githubusercontent.com/16159027/31588522-5a8b48de-b1f3-11e7-8e87-b6823caa7f4f.png)

**Comment by NoahDragon** [comment]
Here is my screenshot. Sorry, I'm not familiar with QT build, there is only one line in the output.

![image](https://user-images.githubusercontent.com/5704064/31591636-9bd488b8-b1ef-11e7-9a03-40dff1afc0e0.png)

**Comment by bonafid3** [comment]
Strange. Please try to create a new Qt project a Qt Gui application and lets see it works or not. Meanwhile I will install Ubuntu to one of the machines in the office to see what is going on.

**Comment by ponzifex** [comment]
I have tried on Mac OS X yet and modified to code to run with OpenGL core profile. You may want to update your source and try it again now. This week I will have an Ubuntu machine so I will be able to try it.

**Comment by ponzifex** [comment]
The MAC version is almost ok, except the textures. VAO was needed for the core OpenGL profile!
<img width="1280" alt="screen shot 2017-10-17 at 11 31 30 am" src="https://user-images.githubusercontent.com/6368578/31682434-e5c06204-b32e-11e7-92f8-e2ed781d3c95.png">

**Comment by ponzifex** [comment]
The textures are working now on MAC OS X!
<img width="1280" alt="screen shot 2017-10-17 at 1 44 24 pm" src="https://user-images.githubusercontent.com/6368578/31688489-591d32d8-b341-11e7-92fe-e85bcb386d80.png">

**Comment by NoahDragon** [comment]
@ponzifex thank you for providing a quick fix. The issue still remains on my Ubuntu system.

The Ubuntu version is 16.04, and QT version is 5.

**Comment by bonafid3** [comment]
Ok, please wait until I can try this on a Linux machine and I will publish the modifications.

**Comment by bonafid3** [comment]
Compiles and runs on Linux too! Tested on Ubuntu 16.04 LTS 32bit with Qt5.5

![screenshot from 2017-10-20 16-41-15](https://user-images.githubusercontent.com/16159027/31826540-a2f46a9a-b5b5-11e7-8c74-d7cf5956b75d.png)

**Comment by NoahDragon** [comment]
@bonafid3 thank you very much. Will give it a try tonight.

**Comment by NoahDragon** [comment]
It works great. Thank you very much!
